# Generated by Django 4.2.1 on 2023-05-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='civility',
            field=models.CharField(choices=[('MONSIEUR', 'Monsieur'), ('MONSIEUR', 'Monsieur'), ('MADAME', 'Madame'), ('EMPTY', 'Empty')], default='EMPTY', max_length=12),
        ),
    ]
