# Generated by Django 4.2.1 on 2023-05-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_civility'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='civility',
            field=models.CharField(choices=[('MONSIEUR', 'Monsieur'), ('MADAME', 'Madame'), ('MADEMOISELLE', 'Mademoiselle'), ('EMPTY', '---')], default='EMPTY', max_length=12),
        ),
    ]
