# Generated by Django 4.2.1 on 2023-05-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_first_name_account_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='activitee',
            field=models.CharField(choices=[('BASEACT', 'Choisir une activité...'), ('SALARIE', 'Salarié'), ('ENTREPRENEUR', 'Entrepreneur'), ('INDEPENDANT', 'Indépendant'), ('SANSEMPLOI', 'Sans emploi'), ('ETUDIANT', 'Etudiant'), ('FONCTIONNAIRE', 'Fonctionnaire')], default='BASEACT', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='adresse1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='adresse2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='pays',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='societe',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
