# Generated by Django 4.2.1 on 2023-05-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_facebook_account_langage_account_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cni_image',
            field=models.ImageField(blank=True, upload_to='files/covers'),
        ),
    ]
