# Generated by Django 4.2.1 on 2023-05-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_account_cni_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cni_image',
            field=models.FileField(blank=True, upload_to='account/files/verification'),
        ),
    ]
