# Generated by Django 4.2.1 on 2023-05-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_account_cni_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='justif_dom',
            field=models.FileField(blank=True, upload_to='account/files/verification'),
        ),
        migrations.AddField(
            model_name='account',
            name='selfie',
            field=models.FileField(blank=True, upload_to='account/files/verification'),
        ),
    ]
