# Generated by Django 4.2.1 on 2023-06-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_account_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='id_compte_wallester',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
